//
//  NewsInteractor.swift
//  LampaTest
//
//  Created George Kyrylenko on 7/29/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RxSwift

class NewsInteractor: NewsInteractorProtocol {
    
    
    weak var presenter: NewsPresenterProtocol?
    
    func getNewNews(page: Int) -> Observable<MovieDataEntity?> {
        return ApiRequset.getTenNews(page: page)
    }
}
