//
//  NewsProtocols.swift
//  LampaTest
//
//  Created George Kyrylenko on 7/29/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import RxSwift

//MARK: Wireframe -
protocol NewsWireframeProtocol: class {

}
//MARK: Presenter -
protocol NewsPresenterProtocol: class {
    func getNewNews(page: Int)
}

//MARK: Interactor -
protocol NewsInteractorProtocol: class {

  var presenter: NewsPresenterProtocol?  { get set }
    func getNewNews(page: Int) -> Observable<MovieDataEntity?>
}

//MARK: View -
protocol NewsViewProtocol: class {

  var presenter: NewsPresenterProtocol?  { get set }
    func setNews(news: MovieDataEntity?)
}
