//
//  NewsPresenter.swift
//  LampaTest
//
//  Created George Kyrylenko on 7/29/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsPresenter: NewsPresenterProtocol {
    
    weak private var view: NewsViewProtocol?
    var interactor: NewsInteractorProtocol?
    private let router: NewsWireframeProtocol

    init(interface: NewsViewProtocol, interactor: NewsInteractorProtocol?, router: NewsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getNewNews(page: Int) {
        self.interactor?.getNewNews(page: page).subscribe({ (news) in
            if news.error != nil{
                
                return
            }
            self.view?.setNews(news: news.element!!)
        })
    }
}
