//
//  NewsRouter.swift
//  LampaTest
//
//  Created George Kyrylenko on 7/29/18.
//  Copyright © 2018 George Kyrylenko. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NewsRouter: NewsWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: NewsViewController) {
        let interactor = NewsInteractor()
        let router = NewsRouter()
        let presenter = NewsPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
    }
}
